language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# Install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

# Run tests
script: python manage.py test

notifications:
   email: a.fiori@cheapnet.it